### ISSUE TITLE
Export Publication and Subscription

### ISSUE THREAD

**Issue by theodorDiaconu** [englue/meteor-publish-composite#101]
So it allows someone like me to hack it and extend your package without modifying very much code.

**Comment by reywood** [comment]
Interesting idea, but exporting these classes would make them part of the public API of this package. Doing so would make future changes more difficult to implement as the backwards compatibility footprint would become much much larger. A better option for you would probably be to simply fork this repo or just copy the code into your project and change as you see fit.
