### ISSUE TITLE
userId is undefined in child publications when using collection hooks

### ISSUE THREAD

**Issue by mvcdev** [englue/meteor-publish-composite#102]
We're using https://github.com/matb33/meteor-collection-hooks package. I already reported this issue there: https://github.com/matb33/meteor-collection-hooks/issues/218 but I'm on which side this issue is.

We have the following publication:
```javascript
Meteor.publishComposite('candidates', function() {
  return {
    find() {
      return Candidates.find();
    },
    children: [
      {
        find(candidate) {
          return Jobs.find(candidate.jobId);
        }
      }
    ]
  };
});
```

We have the following hook:
```javascript
Jobs.before.find(function (userId, selector, options, cursor) {
  // userId is undefined when it's called from children publication
});
```

**Comment by mvcdev** [comment]
Just in case here I created a repo reproducing the issue. Here are  the code: https://github.com/mvcdev/todos/blob/master/imports/api/tasks.js#L7-L36

**Comment by zimme** [comment]
I have a solution for this, will submit a PR later this week.
