### ISSUE TITLE
Keep getting (could be) package errors in server console Meteor 1.4.4.1

### ISSUE THREAD

**Issue by paulincai** [englue/meteor-publish-composite#104]
However everything seems to be working fine for the moment. I am pretty sure I am getting the right data in the pipe.

=> App running at: http://localhost:3000/
I20170425-04:02:34.504(4)? Exception from sub initialMessages id M5Y3wnHoKyzve5hvH TypeError: this.cursor._getCollectionName is not a function
I20170425-04:02:34.505(4)?     at Publication._getCollectionName (packages/reywood:publish-composite/lib/publication.js:79:67)
I20170425-04:02:34.505(4)?     at Publication.publish (packages/reywood:publish-composite/lib/publication.js:21:37)
I20170425-04:02:34.506(4)?     at packages/reywood:publish-composite/lib/publish_composite.js:17:17
I20170425-04:02:34.507(4)?     at Array.forEach (native)
I20170425-04:02:34.507(4)?     at [object Object].publish [as _handler] (packages/reywood:publish-composite/lib/publish_composite.js:15:25)
I20170425-04:02:34.508(4)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20170425-04:02:34.508(4)?     at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1035:17)
I20170425-04:02:34.509(4)?     at [object Object]._.extend._startSubscription (packages/ddp-server/livedata_server.js:853:9)
I20170425-04:02:34.510(4)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp-server/livedata_server.js:625:12)
I20170425-04:02:34.510(4)?     at packages/ddp-server/livedata_server.js:559:43
I20170425-04:02:34.635(4)? Exception from sub initialMessages id vz7zshmGhbLmajkcc TypeError: this.cursor._getCollectionName is not a function
I20170425-04:02:34.635(4)?     at Publication._getCollectionName (packages/reywood:publish-composite/lib/publication.js:79:67)
I20170425-04:02:34.636(4)?     at Publication.publish (packages/reywood:publish-composite/lib/publication.js:21:37)
I20170425-04:02:34.637(4)?     at packages/reywood:publish-composite/lib/publish_composite.js:17:17
I20170425-04:02:34.638(4)?     at Array.forEach (native)
I20170425-04:02:34.638(4)?     at [object Object].publish [as _handler] (packages/reywood:publish-composite/lib/publish_composite.js:15:25)
I20170425-04:02:34.639(4)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1737:12)
I20170425-04:02:34.639(4)?     at [object Object]._.extend._runHandler (packages/ddp-server/livedata_server.js:1035:17)
I20170425-04:02:34.639(4)?     at [object Object]._.extend._startSubscription (packages/ddp-server/livedata_server.js:853:9)
I20170425-04:02:34.640(4)?     at [object Object]._.extend.protocol_handlers.sub (packages/ddp-server/livedata_server.js:625:12)
I20170425-04:02:34.640(4)?     at packages/ddp-server/livedata_server.js:559:43

**Comment by reywood** [comment]
I'm not having any luck reproducing this error. Could you make a GitHub repo with a small meteor project that exhibits this behavior?

**Comment by reywood** [comment]
Closing for now but will reopen if you can shed some more light on the problem.

**Comment by paulincai** [comment]
Will do once I come across this one again. I believe it is happening at the time of logout or mobile app going to background, a time when I possibly lose authorization for the subscriptions.
