### ISSUE TITLE
bindEnvironment for callbacks

### ISSUE THREAD

**Issue by zimme** [englue/meteor-publish-composite#109]
https://github.com/meteor/meteor/pull/8734

Just wanted to let you know about this. For apps on 1.5.1 and later this package doesn't have to bind the environment of the observe/observeChanges callbacks. Don't really know if it's worth the effort of not doing this under certain conditions but just thought I would give you a heads up.

**Comment by reywood** [comment]
Do you know if there are drawbacks to leaving the `bindEnvironment` wrappers in place?

**Comment by zimme** [comment]
I don't really know if running `bindEnvironment` on an already bound function will cause any weirdness, but I would think not... I can look into `bindEnvironment` a bit more this weekend to see if something makes me think different.
