### ISSUE TITLE
Document best practice for publication

### ISSUE THREAD

**Issue by janat08** [englue/meteor-publish-composite#112]
I don't belief that even the meteor guide mentions this, but under the hood meteor operates publications best when updates occur with id selector, and proportionally publications better use the same id selectors. I certainly remember being advised to try and update by id as that is recorded in oplog, but if this performance tip is also contingent on publication selector for that id I don't know, as surely emphasis as on id alone would be pointless.

**Comment by reywood** [comment]
This sounds like something that should be in the documentation for Meteor. I wouldn't expect every package that has to do with publications to also duplicate that info.

**Comment by janat08** [comment]
I belief I created this topic to contest some claim that this package is absolutely performant.

**Comment by reywood** [comment]
Maybe someone else made that claim. I don't think I ever have 😄 .  In any event, there are many occasions when records that should be published to the client can't be selected by ID. And if someone needs to use this package, chances are pretty good they're in that boat. Do you have a link to any more info about this performance issue?

**Comment by janat08** [comment]
Im not sure if publication exactly has to happen by the ID, edit definitely
are best when happening with ID. I think I read 2 articles like that, and
they were pretty old, possibly in 2013 or something.
