### ISSUE TITLE
Published version on atmosphere includes `eslint` (increases package size by at least 16MB)

### ISSUE THREAD

**Issue by SimonSimCity** [englue/meteor-publish-composite#118]
The version currently available at atmosphere includes the npm package `eslint` and some related packages. This increases the size my project by 16MB - by packages which are only used when developing this package.

These packages were most-likely installed because they're listed in the [package.json](https://github.com/englue/meteor-publish-composite/blob/master/package.json) file. Before publishing you called something like `npm install` without the `--production` flag or at least didn't remove the superfluous packages by calling `npm prune --production`.

Would you have the chance and time to republish this package without the npm development packages? Thanks in advance.

**Comment by reywood** [comment]
Thanks for reporting. New version pushed without dev dependencies.
