### ISSUE TITLE
Publish loses reactivity after "load more"

### ISSUE THREAD

**Issue by nazarposhta** [englue/meteor-publish-composite#120]
Hello everyone!
I stacked with a problem of losing reactivity. When I subscribe first time with limit 20 items, everything is fine. But. When I change parameters "limit" (I want to load 20 items more), whole bunch of items loses reactivity. Any ideas?
```
publishComposite('tasks', function(args = {}) {
    if (typeof args !== 'object') {
        return null;
    }
    var selector = generateSelector(args);
    return {
        collectionName: 'tasks-search',
        find() {
            return Tasks.find(selector, {
                sort: { created: -1 },
                limit: args.limit || Meteor.settings.public.pagination_results
            });
        },
        children: taskContents(false, selector)
    };
});
```

**Comment by copleykj** [comment]
I can't say why this happens, but I think that a better pattern here would be to not cancel the first subscription and start a whole new one, but rather start subsequent small publications utilizing skip to publish an *additional* set of results.

**Comment by nazarposhta** [comment]
@copleykj  yea... but. That will be "pagination" on "load more".

**Comment by nazarposhta** [comment]
@reywood  What you think about that problem? Maybe I'm doing something wrong?

**Comment by nazarposhta** [comment]
Ok guys. Everything is fine. I found a problem. That was inside 
`var selector = generateSelector(args);`  Reactivity works perfect. I had to be careful with `selector` object and avoid changing it. `_.extend({}, selector, { _id: task.parent_task_id })` helped me.
