### ISSUE TITLE
Cancel publish

### ISSUE THREAD

**Issue by medihack** [englue/meteor-publish-composite#25]
Within the normal `publish` method there is an easy way to cancel the publish and return nothing (just use `this.ready(); return;`. With `publishComposite` this doesn't work. I get the following exception then: `Exception from sub 2BgTTyL3mgoTmRtbL TypeError: Cannot read property 'children' of undefined`.

How could I just cancel the publish (and publish nothing), for example when some provided parameter is invalid?

**Comment by medihack** [comment]
Ok, it seems a simple `return {find: function() {}}` solves the problem.

**Comment by fpoirier1** [comment]
Would be great something like `this.cancel()` though..

**Comment by reywood** [comment]
@fpoirier1 You can simply `return` from a `find` function to accomplish that.

**Comment by fpoirier1** [comment]
Yes, this is what I am doing right now : 

    var cancel = function(){
      return {find: function() {}}
    }
    
    Meteor.publishComposite('projects', function(){
      // Return nothing if user is not loggedIn
      if(!this.userId)
        return cancel();
        
        ...

I just tought it would have been only cleaner that's all.

**Comment by reywood** [comment]
I discuss that scenario briefly in [this blog post](http://braindump.io/meteor/2014/09/12/publishing-reactive-joins-in-meteor.html).

**Comment by fpoirier1** [comment]
I get your point. Awesome work by the way!
