### ISSUE TITLE
Publish composite with Router

### ISSUE THREAD

**Issue by sivailango** [englue/meteor-publish-composite#26]
'client' collection:
{
    "name" : "Test",
    "code" : "test",
    "createdAt" : ISODate("2015-01-01T20:29:05.290Z"),
    "classifications" : [ 
        {
            "id" : "DS8QAaFnk5XHbcFhH"
        }, 
        {
            "id" : "tFKDJi7s3PFJbHpCu"
        }, 
        {
            "id" : "Htdv9RKrrCbYwPpEt"
        }
    ]
    "_id" : "rzaC7fdmrE6KTgWXF"
}

'classification' collection:
{
    "classification" : "Quick & Dirty Format",
    "isActive" : true,
    "_id" : "DS8QAaFnk5XHbcFhH"
}
{
    "classification" : "Web search",
    "isActive" : true,
    "_id" : "Htdv9RKrrCbYwPpEt"
}
{
    "classification" : "Reformatting",
    "isActive" : true,
    "_id" : "tFKDJi7s3PFJbHpCu"
}

Router:

Router.route('client/:_id', {
	path : 'client/:_id',
	template : 'viewClient',
	name : 'view.client',
	layoutTemplate : adminLayout,
	yieldTemplates : {
		footer: {to: footer}
	},
	data : function() {
		return Client.findOne(this.params._id);
	}
});

Template.viewClient.helpers({
	classifications : function() {
		return WorkClassification.findOne(this.client.classifications.id);
	}
});

Publish composite:

Meteor.publishComposite('client', {
	find: function() {
		return Client.find();
	},
	children: [
		{
			find: function(client) {
				return WorkClassification.find({ _id : client.classifications.id});
			}
		}
	]
});

I could get client info from routes. But exceptions raised on helpers function with return statement for classifications.

I want to display classification from classification collection using classification id from client collection. Already i have done publish composite for other projects.

Can we add more data context for composite?

**Comment by reywood** [comment]
The `classifications` property on your client records is an array, so you can't do `WorkClassification.find({ _id : client.classifications.id});` or `WorkClassification.findOne(this.client.classifications.id);`. You would have to do something like `WorkClassification.find({ _id : { $in: { _.map(client.classifications, function(c) { return c.id; }) } } });`.
