### ISSUE TITLE
Modifying the relation field causes a race condition

### ISSUE THREAD

**Issue by mquandalle** [englue/meteor-publish-composite#29]
Hello,

We encounter an issue in https://github.com/libreboard/libreboard/issues/61 related to the update of data published by `publishComposite` in a environment with latency between the client and the server (it works in local, but we have the bug in production).

I'm not sure what the problem exactly is, it seems to be related to the modification of the field that is used to make the relation in the `publishComposite` function. To make this bug easier to fix I manage to create a minimal reproduction:

> https://github.com/mquandalle/meteor-publish-composite-latency-bug

You can clone the above repository and launch meteor. The UI will say "Max works on Work harder" and a few seconds later "Max works on Play harder". However if you deploy this application (for instance on the meteor cloud) it will not work anymore. I commented the code, but if what's going on is not clear, feel free to ask me here.

**Comment by mquandalle** [comment]
After further investigations I get a better understanding of the problem, and I'll try to expose it here. Basically there is a race condition if you update the field that is used to make the `publishComposite` relation.

Let me explain the example linked above. We have two collection with a `1..n` relation between them. There is a list of `Tasks`, and some `Workers` each being assigned to a single task.

```js
Tasks = new Mongo.Collection('tasks');
Workers = new Mongo.Collection('workers');
```

We feed the database with a one worker and two tasks (A and B) and we assign the worker to the task A (by `_id`).

```js
Tasks.insert({_id: "taskA", title: "A"});
Tasks.insert({_id: "taskB", title: "B"});
Workers.insert({_id: "worker1", name: "1", assignedTask: "taskA"});
```

Then come our publication. We want to publish all tasks, and for each task publish the workers that are assigned to it — if any.

```js
Meteor.publishComposite('tasksAndAssignedWorkers', function () {
  return {
    find: function () {
      return Tasks.find();
    },
    children: [
      {
        find: function (task) {
          return Workers.find({assignedTask: task._id});
        }
      }
    ]
  }
});
```

On the client we subscribe to this publication:

```js
Meteor.subscribe('tasksAndAssignedWorkers');
```

And we try to change the assigned task of `worker1` from `taskA` to `taskB`:

```js
Workers.update("workerA", {$set: {assignedTask: 'taskB'}});
```

Which translates into the following DDP message:

```json
[{
  "msg": "method",
  "method": "/workers/update",
  "params": [{"_id": "worker1"},
  {"$set": {"assignedTask": "taskB"}}, {}],
  "id": 1
}]
```

This call causes a race condition on the publication function, sometimes we will receive these DDP messages:

```json
[{
  "msg": "result",
  "id": "2",
  "result": 1
}]
[{
  "msg": "removed",
  "collection": "workers",
  "id": "worker1"
}]
[{
  "msg": "added",
  "collection": "workers",
  "id": "worker1",
  "fields": {
    "name": "A",
    "assignedTask": "taskB"
  }
}]
[{
  "msg": "updated",
  "methods": "2"
}]
```

Note that the worker document is not being updated, but first removed and then re-added (sending again all the field we already know).

And sometimes we will receive these DDP messages:

```json
[{
  "msg": "result",
  "id": "2",
  "result": 1
}]
[{
  "msg": "updated",
  "methods": "2"
}]
```

ie, no documents modification, and the operation that happened on the client is reverted by this response from the server.

@reywood Do you have any idea how to fix this?

**Comment by reywood** [comment]
Thanks for the incredible detailed report. I'll delve into this and see if I can figure it out.

**Comment by mquandalle** [comment]
Note that the problem I had in LibreBoard was fixed in https://github.com/libreboard/libreboard/commit/6c73ac317d6a7c5efb2c82975ca3e6a2f049e3a9. But the bug reported here still stands.

**Comment by reywood** [comment]
A new version has been released that may fix this issue. I didn't have much luck replicating your problem, but this release fixes some odd behavior I was seeing that seemed somewhat related. I know you've updated your project to avoid this issue, so I have no expectation that you'll test this. Going to close this issue, but feel free to re-open it if you experience this problem again.

**Comment by fpoirier1** [comment]
I'm facing the same issue. I'm using v1.3.6. I'm not too sure how I can bring more details than what @mquandalle reported...

**Comment by reywood** [comment]
If you could put together a minimal Meteor app that exhibits the issue, that would be extremely helpful. As it is, I haven't been able to reproduce the problem.
