### ISSUE TITLE
soop integrates publish-composite

### ISSUE THREAD

**Issue by miguelalarcos** [englue/meteor-publish-composite#33]
Hi, I would like to tell you about my new package ```soop```, [Simple Object Oriented Programming](https://github.com/miguelalarcos/soop), where I integrate ```publish-composite```.
I tell you if you had an opinion about the integration of your packages.
I'm still not sure if that kind of programming is useful with Meteor, but I want to give it a try. Thanks for your attention.

**Comment by reywood** [comment]
Feel free to use this code however you see fit :)
