### ISSUE TITLE
strange error..

### ISSUE THREAD

**Issue by pociej** [englue/meteor-publish-composite#35]
I20150327-16:37:13.264(1)? Exception in queued task: TypeError: Object #<Object> has no method '_getCollectionName'
I20150327-16:37:13.264(1)?     at Publication._getCollectionName (packages/reywood:publish-composite/lib/publication.js:74:1)
I20150327-16:37:13.264(1)?     at Publication.publish (packages/reywood:publish-composite/lib/publication.js:15:1)
I20150327-16:37:13.264(1)?     at Publication.createChildPublication (packages/reywood:publish-composite/lib/publication.js:81:1)
I20150327-16:37:13.264(1)?     at Array.forEach (native)
I20150327-16:37:13.264(1)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150327-16:37:13.264(1)?     at Publication._publishChildrenOf (packages/reywood:publish-composite/lib/publication.js:78:1)
I20150327-16:37:13.264(1)?     at Object.added (packages/reywood:publish-composite/lib/publication.js:30:1)
I20150327-16:37:13.265(1)?     at [object Object].observeChangesCallbacks.added (packages/minimongo/observe.js:153:1)
I20150327-16:37:13.265(1)?     at self.applyChange.added (packages/minimongo/observe.js:53:1)
I20150327-16:37:13.265(1)?     at packages/mongo/observe_multiplex.js:183:1

**Comment by reywood** [comment]
Do you happen to know what version of meteor you're running?

**Comment by pociej** [comment]
i 1.0.4 or 1.0.5 , same error in both cases

**Comment by reywood** [comment]
Sounds like perhaps one of your `find` functions is not returning a cursor. Could you post your `publishComposite` routine?

**Comment by pociej** [comment]
sorry man , you are right , there is findOne by accident. Thx a lot and sorry one more time

**Comment by reywood** [comment]
No worries
