### ISSUE TITLE
Multiple cursors

### ISSUE THREAD

**Issue by darkadept** [englue/meteor-publish-composite#36]
In Meteor's regular publish function I can return an array of cursors for different collections. Is there a way to do this with publishComposite?

**Comment by reywood** [comment]
Hmm, I can't really envision how that would work in the context of this package. How would you envision child publications working?

**Comment by darkadept** [comment]
Alas I don't really have a vision how it would work. I did get around it by returning a dummy cursor of 1 result as my top level document and then just using the 1st level children as multiple top level cursors. Then each "top-level" cursor can have children and so on as per normal.

I guess one way would be to have the option to say "no ultimate top level cursor". There are probably other ways as well.

**Comment by reywood** [comment]
You may be better off splitting those into multiple publications.

**Comment by hellogerard** [comment]
I ran into this issue as well, since I had multiple queries for a particular publication.

Currently, the 2nd param is an object literal or a function that returns one. I was envisioning that the 2nd param could be either an array of object literals, or an array with a literal and a cursor, or a function that returns either. This keeps somewhat the same pattern as regular `Meteor.publish`.

Just my $0.02. Not sure how hard it would be to code.

**Comment by jasonszhao** [comment]
Splitting off to multiple publications would be terribly annoying if I wanted to return a big compilation of data that came from multiple sources.

**Comment by mordra** [comment]
I have the same requirements for a 'startup' publication where I have one cursor that has dependencies but another cursors which is just by itself.
```
Meteor.publishComposite('startup', {
    find: function () {
        Mk.debug('[Publish] startup: user(%s)', this.userId);
        return Db.Organisations.find();
    },
    children:[
        {
            find: function () {
                return Meteor.users.find(this.userId);
            },
            children: [
                {
                    find: function (user) {
                        return Db.Patients.find({
                            _id: {$in: user.patients}
                        });
                    }
                }
            ]
        },
        {
            find: function () {
                return Db.Organisations.find({}, {fields:{name:1}})
            }
        }
    ]
});
```

However, I'm guessing that if my top find function doesn't change then the children won't get rerun, therefore I don't think that @darkadept solution works unless the dummy cursor contains all the cursors below it?

**Comment by bubuntux** [comment]
i'm running into something similar, i'll try to simplify my scenario using coffescript

    # collections.coffee (lib/)
    Players = new Mongo.Collection 'players'
    Games = new Mongo.Collection 'games' 

    # publish.coffee (server/)
    Meteor.publishComposite 'game', (gameKey) ->
      check gameKey, String
      collectionName: 'me'
      find: -> Players.find _id: Meteor.userId(), gameKey: gameKey
      children:
        [
          find: (player) -> Players.find {gameKey: gameKey}, {fields: {secretInfo: player.awesome?}}
        ]
        
but on the same subscribe i also want to return a cursor for the game
    
    Games.find gameKey, limit: 1
    
which doesn't really depends on the players

i know i can publish that extra cursor separately, but would be nice to have the option to publish multiple cursors

**Comment by reywood** [comment]
Finally got to this. You can now publish multiple top level cursors using one of the two forms below.

```javascript
Meteor.publishComposite('myPub', [
    {
        find: function() {
            return MyCollection1.find({});
        },
        children: [
            // ...
        ]
    },
    {
        find: function() {
            return MyCollection2.find({});
        },
        children: [
            // ...
        ]
    }
]);

Meteor.publishComposite('myPub', function() {
    return [
        {
            find: function() {
                return MyCollection1.find({});
            },
            children: [
                // ...
            ]
        },
        {
            find: function() {
                return MyCollection2.find({});
            },
            children: [
                // ...
            ]
        }
    ];
});
```

**Comment by bubuntux** [comment]
Awesome! :thumbsup:

**Comment by hellogerard** [comment]
Hey, thanks!

**Comment by mordra** [comment]
This makes me happy :smile:

**Comment by JulianKingman** [comment]
Super handy, can you add a note to this in the documentation? Where it says:
"An object literal specifying the configuration of the composite publication or a function that returns said object literal"
Instead say:
"An object literal specifying the configuration of the composite publication or a function that returns said object literal (or an array of object literals)"
And including it in one of the examples would be awesome.
