### ISSUE TITLE
publish composite returns the docs in two collections client side

### ISSUE THREAD

**Issue by tdmoneybanks** [englue/meteor-publish-composite#40]
I am using publish composite and it is returning the docs into their own respective collections on the client as opposed to just one collection. Here is my code:
```
Meteor.publishComposite('userAchievements', {
	find: function() {
		if (!this.userId) {
			return;
		}
		var user = Meteor.users.findOne({ _id: this.userId });
		//Meteor._debug(user);
		if (!user.profile.xuid) {
			Meteor._debug("no xuid");
			return;
		}
		return collectionOne.find({ userId: this.userId });
	},
	children: [
		{
			find: function(collectionOne) {
				return collectionOne.find({ _id: collectionOne.collectionTwoId });
			}
		}
	]
});
```
How would I get it to just return one cursor?

**Comment by reywood** [comment]
Check out [this blog post](http://braindump.io/meteor/2014/09/20/publishing-to-an-alternative-clientside-collection-in-meteor.html). It describes the use of the `collectionName` option.
