### ISSUE TITLE
Publishing large documents causes Exception from task: [RangeError: Maximum call stack size exceeded]

### ISSUE THREAD

**Issue by helfer** [englue/meteor-publish-composite#45]
Returning a large document in a find that has children defined seems to cause the following error: Exception from task: [RangeError: Maximum call stack size exceeded]

A workaround that works fine in my case is to limit the publication in the find to only the fields that are needed for the child subscription, but it won't work for you if you need the whole document.

In my example, documents in the exam collections have a field that contains a rather large object. 

Doing this works fine:

```javascript
Meteor.publishComposite( 'examSolutions', function( examId ){
  return {
    'find': function() {
        return Exams.find( { _id: examId}, { fields: { defaultGradingSchemeId: true } } );
      }
    },
    children: [
      {
        find: function( exam ){
          return Solutions.find( { examGradingSchemeId: exam.defaultGradingSchemeId } );
        }
      }
    ]
  };
});
```

But doing the following will cause the range error:

```javascript
Meteor.publishComposite( 'examSolutions', function( examId ){
  return {
    'find': function() {
        return Exams.find( { _id: examId} );
      }
    },
    children: [
      {
        find: function( exam ){
          return Solutions.find( { examGradingSchemeId: exam.defaultGradingSchemeId } );
        }
      }
    ]
  };
});
```

Here is the full stack trace:
```
Exception from sub examSolutions id rkCwGzF6S3n8PxkEt [object Object]
at Object.Future.wait (/home/user7/.meteor/packages/meteor-tool/.1.1.3.iasc1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
at [object Object]._.extend.runTask (packages/meteor/fiber_helpers.js:81:1)
at [object Object]._.extend.addHandleAndSendInitialAdds (packages/mongo/observe_multiplex.js:47:1)
at [object Object].MongoConnection._observeChanges (packages/mongo/mongo_driver.js:1179:1)
at [object Object].Cursor.observeChanges (packages/mongo/mongo_driver.js:854:1)
at Function.LocalCollection._observeFromObserveChanges (packages/minimongo/observe.js:177:1)
at [object Object].Cursor.observe (packages/mongo/mongo_driver.js:848:1)
at Publication.publish (packages/reywood:publish-composite/lib/publication.js:18:1)
at [object Object]._handler (packages/reywood:publish-composite/lib/publish_composite.js:12:1)
at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
```

Obviously for large documents passing the entire document as an argument to the added, changed or removed function of observe is not going to work, but maybe we can explicitly specify which fields the child subscriptions need to know and pass an object that's been reduced to only the _id and those fields.

**Comment by reywood** [comment]
From the looks of the stack trace, I don't think this has to do with the child publication. The `Maximum call stack size exceeded` error indicates that there's a recursive function that's recursing too much. Looking at the [wait function in the fibers library](https://github.com/laverdet/node-fibers/blob/master/future.js#L415) (which appears to be generating this error and is recursive), it looks like it may be waiting too long. Perhaps your exam document is too big too publish in a reasonable amount of time. If that's the case, this would need to be addresses in meteor itself or the fibers library. Could you try commenting out the `children` block and see if you still get the same error?

**Comment by helfer** [comment]
You're right! After trying around a little bit, I found that the problem was not the document size, but probably an infinite recursion when some method tried to serialize the exam object to pass it around ( it contains a tree with circular references). Simply adding ```{ transform: null }``` made the problem go away.

I think it's probably worth mentioning in the documentation that if there is a transform defined on the collection it will be run and might cause problems. Even though it's obvious if you think about it for a second, the behavior differs from the normal publish function, where published documents will not be transformed before they are sent to the client.

I'm still not sure why passing around the exam object on the server causes a problem, but somehow there must be a place where it's being serialized for some reason? If it's possible to apply the transform after that point, for example just before passing it into the child subscription function, that might be worth trying?

**Comment by etyp** [comment]
@helfer @reywood We're experiencing a "RangeError: Maximum call stack size exceeded" as well after implementing a publish composite on a collection that publishes siblings of the same collection in the `children` array.

We've tried to track down the issue in every corner of our app, and it seems to happen when collections matching the pub are updated with `{ multi: true }`.

Any ideas based on the stack trace below?

```
       stack:  
        [ 'RangeError: Maximum call stack size exceeded', 
          '---------------------------------------------', 
          '    at Object.setImmediate [as _setImmediate] (packages/meteor.js:323:14)', 
          '    at Object._.extend.defer (packages/meteor.js:514:12)', 
          '    at /bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/oplog_observe_driver.js:487:14', 
          '    at Object.Meteor._noYieldsAllowed (packages/meteor.js:671:12)', 
          '    at OplogObserveDriver._fetchModifiedDocuments (/bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/oplog_observe_driver.js:483:12)', 
          '    at /bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/oplog_observe_driver.js:645:18', 
          '    at Object.Meteor._noYieldsAllowed (packages/meteor.js:671:12)', 
          '    at OplogObserveDriver._handleOplogEntrySteadyOrFetching (/bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/oplog_observe_driver.js:575:12)', 
          '    at OplogObserveDriver.proto._handleOplogEntrySteadyOrFetching (packages/meteorhacks_kadira.js:2913:53)', 
          '---------------------------------------------', 
          '    at Object.setImmediate [as _setImmediate] (packages/meteor.js:323:14)', 
          '    at Object._.extend.defer (packages/meteor.js:514:12)', 
          '    at OplogHandle._maybeStartWorker (/bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/oplog_tailing.js:253:12)', 
          '    at /bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/oplog_tailing.js:242:14', 
          '    at loop (/bundle/bundle/programs/server/packages/meteor:/?app/packages/mongo/mongo_driver.js:1146:9)', 
          '    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)', 
          '    at packages/meteor.js:445:45', 
          '    at runWithEnvironment (packages/meteor.js:1176:24)', 
          '---------------------------------------------', 
          '    at handleOperationCallback (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:454:24)', 
          '    at /bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:490:9', 
          '    at authenticateStragglers (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:429:16)', 
          '    at [object Object].messageHandler (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:463:5)', 
          '    at Socket.<anonymous> (/bundle/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:309:22)', 
          '    at emitOne (events.js:77:13)', 
          '    at Socket.emit (events.js:169:7)', 
          '    at readableAddChunk (_stream_readable.js:153:18)', 
          '    at Socket.Readable.push (_stream_readable.js:111:10)' ] } 
```
