### ISSUE TITLE
compatibility with meteorhacks:unblock

### ISSUE THREAD

**Issue by dohomi** [englue/meteor-publish-composite#48]
Hello,
I would like to know if there is any plan of supporting `meteorhacks:unblock`inside of this package. The unblock package helped a lot to improve the page speed on my app. Did you have any experience with it? Thanks

**Comment by serkandurusoy** [comment]
I've been using it for a while without any problems.

**Comment by dohomi** [comment]
Hi @serkandurusoy how do you use it? Could you paste an example? Thanks!

**Comment by serkandurusoy** [comment]
Take a look at the following for an example. The only doubt I have is if I am overusing it.

Also, `this.unblock` should not be used for publications where you have other subscriptions that depend on waiting for this one to be ready.

```javascript
Meteor.publishComposite('pubName', function() {
  this.unblock();
  return {
    find: function() {
      this.unblock();
      return ParentCollection.find();
    },
    children: [
      {
        find: function(parent) {
          this.unblock();
          return ChildCollection.find({parentId: parent._id});
        }
      }
    ]
  };
});
```

**Comment by dohomi** [comment]
Thanks for this. I'll check it out soon.

**Comment by lukasvan3l** [comment]
When I try that out, I get this error :(

```
Exception from sub MYSUB id EH6Zf6wB9XgThxbgC TypeError: Object [object Object] has no method 'unblock'
```

**Comment by nkahnfr** [comment]
@lukasvan3l I had the same issue when using by mistake an arrow function to define the publication function. More details here: [Common Meteor Patterns in ES2015 - Publications](https://themeteorchef.com/snippets/common-meteor-patterns-in-es2015/#tmc-publications).
Not sure it's the same issue you have but if it could help.

**Comment by lukasvan3l** [comment]
That was in deed my problem! Sorry, didn't post my solution here...
