### ISSUE TITLE
Fetches leading up to return query in find are not running reactively.

### ISSUE THREAD

**Issue by evolross** [englue/meteor-publish-composite#54]
I've been using `mrt:reactive-publish` successfully but I wanted to give `publish-composite` a try since it's kept up to date and the doc says it's reactive.  I'm having trouble getting the following publication to update reactively.  It doesn't use any children queries, but it needs to call a couple of fetches to pass into the final return query :

    Meteor.publishComposite('biddersByProduct', function(productId) {
        return {
            find: function() {
                console.log("biddersByProduct is running...");
                var physicalBids = PhysicalBids.find({productId: productId}).fetch();
                var onlineBids = OnlineBids.find({productId: productId}).fetch();
                var combinedBidIds = _.union(_.pluck(physicalBids, "bidderId"), _.pluck(onlineBids, "bidderId");
                return Bidders.find({_id: {$in: combinedBidIds}});
            }
        }
     });

Basically a `Bidder` can create several different `PhysicalBids` and `OnlineBids` on a `Product`. So one of my templates is a product page that needs to show all the `Bidders` across all `PhysicalBids` and `OnlineBids`... reactively.

Is something like this meant to be supported reactively?  I don't need any other child collections - just the top level one.  But the way my database is set up - it needs to fetch like this.  So far I have not been able to get it to work.  The `console.log` call only fires upon template loading and never again. The idea is that it fires every time a new `Bidder` creates a `PhysicalBid` or `OnlineBid` on a particular `Product`. It works using `mrt:reactive-publish`.

NOTE: In `mrt:reactive-publish` I have to add `{reactive: true}` to the fetch calls and the final return query, but I think that was just a flag for `reactive-publish`.

**Comment by reywood** [comment]
Only the cursor returned by your `find` function is observed for changes. The only way to do this currently would be to have each query in its own `find` function with each successive query in a child `find`. Of course, that means you'll be publishing all the docs from all your queries. An option to not publish the cursors from specific `find` functions may be added in the near future.

**Comment by evolross** [comment]
Thanks for the info. I was trying to figure out how to re-write the query to make it `publish-composite` friendly, but the problem is I actually need to query the children first to get the set of `ids` to pass to the parent query.  If you can have **two** parent queries (like siblings) it might work (one for `PhysicalBids` one for `CombinedBids`, then they both have a child query that finds `Bidders`).  Would something like that work?  I get the feeling it has to all roll into one singular parent `find` query.

I need to them to ultimately roll into one query so I can iterate over them together in an integrated, mixed, ranked listing (which I sort out in the client helper function). This is important for my application.  I can't do:

    {{#each PhysicalBiddersByProduct}}
        ...
    {{/each}}
    {{#each OnlineBiddersByProduct}}
       ...
    {{/each

I need to do:

    {{each OverallBiddersByProduct}}
        ...
    {{/each}}

**Comment by reywood** [comment]
Ah, I see. It doesn't look like 'publishComposite` is a good fit in that case.

**Comment by patrickml** [comment]
@evolross think of `publishComposite` as a way to get the data to the client and use a package like `https://github.com/dburles/meteor-collection-helpers` to manage your relationships.

**Comment by reywood** [comment]
It occurred to me that you could accomplish what you're trying to do with the following.

```javascript
Meteor.publishComposite('biddersByProduct', function(productId) {
    return [
        {
            find: function() {
                return PhysicalBids.find({productId: productId});
            },
            children: [
                {
                    find: function(physicalBid) {
                        return Bidders.find({_id: physicalBid.bidderId});
                    }
                }
            ]
        },
        {
            find: function() {
                return OnlineBids.find({productId: productId});
            },
            children: [
                {
                    find: function(onlineBid) {
                        return Bidders.find({_id: onlineBid.bidderId});
                    }
                }
            ]
        }
    ];
});
```

**Comment by evolross** [comment]
Yes that works! Thanks for the support and getting me there.  It's what I was saying above about having "two parent" queries as "siblings" but I didn't think to just array the "parent siblings".  Very cool.

I also really like how on the template helper side the code is the same even if I'm trying to get the "children" `Bidders` objects.  It's still just `Bidders.find()` in the JavaScript.  I don't have to do anything special because they were returned in children queries.
