### ISSUE TITLE
date field is not published

### ISSUE THREAD

**Issue by bilalahmed70** [englue/meteor-publish-composite#56]
publishing is working fine and it's publishing all fields except dateCreated which ISODate. Not sure what am I missing. Here is the record looks like:

{ "_id" : "CxRom6TvkAX8mLzh5", "text" : "Another group", "creatorId" : "xiZww8jsJQyvjeybG", "dateCreated" : ISODate("2015-08-22T06:27:37.169Z"), "creatorUsername" : "+1408111111" }

Thanks.

**Comment by reywood** [comment]
Can't comment without seeing what your publication looks like.

**Comment by po-jo** [comment]
same here, a publication like :
```
publishComposite('collection', function(params){
return params.map(param => {
    return {
      find() {
        return Collection.find(query(param))
      }
    }
  })
})
```

with collection {"_id", "text", "author", "fields", "date"} is not reactive for date field  (it's reactive for other fields). @Beelal did you fix your bug ?

**Comment by reywood** [comment]
Sorry to hear you're having trouble. Unfortunately, without a working example app that exhibits the behavior, it's very difficult to speculate on possible solutions.

**Comment by po-jo** [comment]
oops @reywood  I just saw your comment, sorry for the delay :/ 
Finally I have switched to regular publications !
