### ISSUE TITLE
Subscribtions break with lot of data

### ISSUE THREAD

**Issue by fdelia** [englue/meteor-publish-composite#58]
I'm not sure if this is my fault: I love the package, but I had an issue in an app of mine (where rows would not be send, even if they were published). I tried to reproduce the issue with one of your example-repos and came across other issues. I built [this repo](https://github.com/fdelia/reywoods-meteor-publish-composite).

Issues
* Simple subscribtion raises the exception ` Exception in queued task: TypeError: Cannot call method 'apply' of undefined`
<img width="736" alt="screen shot 2015-09-12 at 13 43 32" src="https://cloud.githubusercontent.com/assets/12441906/9831366/4b61b482-5954-11e5-8b01-8ee0e60fa301.png">
* If the same subscribtion is going on twice at the same time, the same exception is thrown multiple times.

In the first case the front-end receives all rows. In the second case it doesn't.

Again: I'm not sure if it's my malpractice.

**Comment by reywood** [comment]
This is the publication from your repo:

```javascript
Meteor.publishComposite('article', function(articleId) {
    return {
        find: function() {
            return Articles.find({ _id: articleId });
        },
        children: [
            {
                collectionName: 'relatedArticles',

                find: function(article) {
                    return Articles.find({ relatedTo: article._id });
                },

                children: [{
                    find: function(relArticle){
                            return Authors.find({ hasWritten: relArticle._id });
                          }
                        }]
            }, {
                // the author of this one
            }
        ]
    };
});
```

Note the spot where you have `// the author of this one`. There's no `find` function present which is what causes the `Cannot call method 'apply' of undefined` error.

**Comment by fdelia** [comment]
This makes sense. Thx!

**Comment by imajus** [comment]
This should definitely be handled in better way than displaying that common error message. I've faced the same problem because I've been planning and testing my publication structure and left some blocks there like this:
```
// Votes
{
	//TODO
},
// Models
{
	//TODO
}
```
I've realized that's a problem only because of this thread here. I couldn't even think that can be the problem.
