### ISSUE TITLE
Silent error if `children` isn't an array.

### ISSUE THREAD

**Issue by MichaelJCole** [englue/meteor-publish-composite#62]
Hi, awesome package.  Thanks!

Hey, I ran into a sticky error that might cause others issues.  I had `children: {...}`, but the children weren't getting to the client.  `children: [{...}]` worked.

Cheers!

Mike

**Comment by zimme** [comment]
We should probably just run `prepareOptions` on `options.children` as well as `options`

**Comment by reywood** [comment]
Added a `check` on all options fields
