### ISSUE TITLE
Collections from publishComposite no longer reactive in Meteor 1.2.1?

### ISSUE THREAD

**Issue by omar-otieku** [englue/meteor-publish-composite#73]
Hello,
I see that publish-composite latest is as of 0.9.0. I am on 1.2.1 and can confirm that collections published with Meteor.publishComposite are no longer reactive. Is there any updates coming in the near future for 1.2.1 support?

**Comment by crazybaud** [comment]
+1

**Comment by nadeemja** [comment]
Working here.

**Comment by dpatte** [comment]
works great for me as well.

**Comment by omar-otieku** [comment]
Yes, I actually had some flawed logic that was getting in the way. Sorry for the false alarm.
