### ISSUE TITLE
Any way to use this on server side?

### ISSUE THREAD

**Issue by luixal** [englue/meteor-publish-composite#74]
My idea was to use this from restivus methods, but I don't see any way to use it on server side. Any idea?

Thanks!

**Comment by sabativi** [comment]
I am not sur i understand what you want.
Restivus is for building REST api with REST endpoints and meteor-publish for making publications, so right now i do not see how to mix the two...

**Comment by luixal** [comment]
Hi,

Maybe it doesn't seem obvious as they're intented for different things... Let's take the first, publishing posts with author information. Now, I want to make that info available in two different places: to the client and to a mobile app (through a REST API), I'd have to write double code (not exactly the same, but quite similar and with the same target): once of the publish-composite and another time on the API endpoint.

It would be great if that logic (for getting post's author in that example) could be written in common code and re-use it.

**Comment by sabativi** [comment]
True, it would be good.

The only way, I can think of right now is just first to define functions

```
var findTopLevelDocument = function(){
    ... 
    return cursorTopLoveldocument
}

var children = function(topLevelDocument){
    ... 
    return cursorSecondLevelDocument
}
```

So that you can write :

```
Meteor.publishComposite('name', function() {
  return {
    find: function(){
      return findTopLevelDocument()
    },
    children: [{
      find: function(topLevelDocument){
        return children(topLovelDocument)
      }
    }]
  }
})
```

and 

```
Api.addRoute('name', {
  get: function () {
    return (
        data : findTopLevelDocument().map(function(topLevelDocument){
             return children(topLovelDocument)
        })
     )
  }
});
```

Perhaps someone else has a better idea ?

**Comment by luixal** [comment]
In fact, that's what I'm doing right now :)

I think I was hoping to find something like a collection2 or something similar, but relation-powered, which doesn't seem to exist :(

**Comment by devwax** [comment]
@luixal [Reactive GraphQL](http://info.meteor.com/blog/reactive-graphql) is on the horizon and will address many of these issues.

> 1. Simple and efficient bindings for GraphQL that make it easy to publish data from REST services, SQL, and MongoDB.

The high-level design is being worked out here: [Apollo High-level Design](https://github.com/apollostack/apollo/blob/master/design/high-level-reactivity.md).

**Comment by luixal** [comment]
Sounds great, but if it's based on REST services, maybe the lack of reactiveness is quite relevant. Haven't read it through (just a quick overview) but I think I saw something about DDP connections.

Will have some detailed reading later on.

Thanks @devwax ! :)

**Comment by reywood** [comment]
Don't have the free time to explore a redesign like this. Feel free to fork this project if you're so inclined.
