### ISSUE TITLE
Small "Gotcha!" with Arrow Functions

### ISSUE THREAD

**Issue by Siyfion** [englue/meteor-publish-composite#81]
If you attempt to use an ES6 Arrow Function as the function used in a child's `find` function, it **will not run**

**Comment by ffflorian** [comment]
Same here. But I'm not sure if this is a `publishComposite` or a Meteor error.
I have a helper in my template:
```js
clientData: function () {
    return Data.findOne({ clientID: this._id }, {sort: { createdAt: -1, limit: 1 } });
},
```
When using `clientData: () => {` I get `Exception in template helper: TypeError: Cannot read property '_id' of undefined`. With `clientData: function () {` it works fine.

**Comment by reywood** [comment]
Having trouble recreating this problem. Keep in mind that arrow functions do not create their own `this` context, but instead inherit it from the context in which they are defined. This should be fine if the arrow function is defined within a function that is passed to publishComposite. However, if you are using the non-function syntax (`Meteor.publishComposite('foo', { find: () => { ... } });`) and you try to access `this.user` in your `find` function, it's not going to work.

Closing for now, but will reopen if someone creates a GitHub repo that demonstrates the problem.
