### ISSUE TITLE
Can this work with FindFromPublication?

### ISSUE THREAD

**Issue by trajano** [englue/meteor-publish-composite#82]
Is it possible to make this work with FindFromPublication?  I think both your code and FindFromPublication wrap `Meteor.publish` though I am trying to see how to get both of them working at the same time.

**Comment by timmyg** [comment]
@trajano ever get this working?

**Comment by reywood** [comment]
As @timmyg discovered, you could probably make this work using the `collectionName` option. Check out [this blog post](http://braindump.io/meteor/2014/09/20/publishing-to-an-alternative-clientside-collection-in-meteor.html) for more info.
