### ISSUE TITLE
how to waitOn data ready using iron-router  and publish-composite

### ISSUE THREAD

**Issue by obrianjunior** [englue/meteor-publish-composite#83]
if have the following route : 

```javascript
this.route('groupPage', {
    path: '/group/:_groupId',
    waitOn: function() {
        return Meteor.subscribe("groupPage", this.params._groupId);
    },
    data: function() {
        var group = Groups.findOne({_id: this.params._groupId});
        var members = Meteor.users.find({_id : {$in: group.memberIds}}); // ******** ISSUE HERE******

        return {
            group: group,
            members: members,
        };
    }
});
```

and the following publication : 

```javascript
Meteor.publishComposite('groupPage', function(groupId, sortOrder, limit) {
    return {
        // return the group
        find: function() {
            if (this.userId) {
                var selector = { _id: groupId };
                var options = { limit: 1 };

                return Groups.find(selector, options);
            }
            else {
                return;
            }
        },


        children: [
            {  // return the members
                find: function(group) {
                    var selector = { _id: { $in: group.memberIds } };
                    return Meteor.users.find(selector);
                }
            }
        ]
    };
});
```

Now my issue is that :  when the related page renders for the first there is no problems but when i actualize the group Page view  the   line : `var members = Meteor.users.find({_id : {$in: group.memberIds}});`  gives me the error : undefined object don't have memberIds property. i guess it's because the subscription is not yet ready when doing  group.memberIds , isn't it ?   Please a hint.
Thanks.

**Comment by reywood** [comment]
In your `data` function, check to make sure the `group` variable is not `undefined` before you try to access `group.memberIds`. I suspect this is more an issue with iron-router, so you may have better luck posting this issue over on their issues page.

**Comment by obrianjunior** [comment]
@reywood   thanks for your reply !   You are right : in fact subscriptions are non-blocking ; and waitOn feature in iron-router waits until the subscription is ready but not  in the data : function () { //etc } . Meaning that when i find a group in data it's not yet available on the client. that's why it returns undefined.
