### ISSUE TITLE
Optional publications / performance

### ISSUE THREAD

**Issue by sakulstra** [englue/meteor-publish-composite#92]
I wonder how to handle optional publications properly.
Imagine a schema like:
```js
// Main
_id: String,
refId: String, optional
// Child
_id: String
```

Than I'd do:
```js
Meteor.publishComposite('lessons.list', {
    find() {
      return Main.find({}, { fields: { _id: 1, refId: aaa } });
    },
    children: [
      {
        find(main) {
          // if (!main.refId) return;
          return Child.find({ _id: main.refId });
        },
      },
    ],
  });
```

I had some performance problems with that, as refId could be undefined and than all the children will be published so I just prefixed this with `if (!main.refId) return;` - which is not exactly valid according to the docs, as one should always return a valid collection pointer.

Is this the right way to handle optional publications or is there a better way?
Best regards,
Lukas

**Comment by reywood** [comment]
Yes, that would be the correct way to do it. If a `find` function returns null or undefined, then publishComposite knows to skip it.
