### ISSUE TITLE
Is this package being maintainable by the authors?

### ISSUE THREAD

**Issue by nlhuykhang** [englue/meteor-publish-composite#96]
I just want to know if the authors still have interests to work on this package?, if not do you have any plans to transfer the job to others or to add some collaborators?

I also want to say thank you, it is a great package so far 👍 
@reywood

**Comment by brylie** [comment]
Great package. We are also concerned whether or not we should be using this package, as there has been no development activity since 2015. Should we still be using this package?

**Comment by reywood** [comment]
Still around. I don't get a lot of free time to work on this package, but it does happen occasionally.
