### ISSUE TITLE
No error logged / reported if find() throws an exception

### ISSUE THREAD

**Issue by damonmaria** [englue/meteor-publish-composite#97]
Is this expected behaviour? Spent ages trying to solve a problem that turned out to be because of this. Even if my find method is:

```
find: () => {
  throw new Error()
}
```

Nothing is logged out in the server console.

**Comment by reywood** [comment]
Could not recreate the problem. I tried testing with the publication below. Error was shown in the terminal when subscribing.

```javascript
import { Meteor } from 'meteor/meteor';

Meteor.publishComposite('throwError', {
    find: function find() {
        throw new Error('This is a test error');
    },
});
```

P.S. Note that if you use arrow functions for your `find` function, you will not have access to the subscription context via `this` inside the function.

**Comment by damonmaria** [comment]
Strange. I'll try and make a small repo test case.
